### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by whitered** [anshuman23/tensorflex#33]
Sorry to open one more issue, but it looks like the problem with segmentation faults is in the library.
So yesterday’s fix solved the problem with finding Tensorflow.so file, and I was able to run simple operations - reading graph and getting graph ops. But I continued to get segfaults on more complex usage. 
Today I was about to reinstall my OS X completely, but before doing that I asked my collegue to test tensorflow on his machine, and he reproduced the segfaults though he has clean C API 1.9.0 installation. 
We both tried to run tensorflex tests, and both catched segfaults:
On my system (OSX 10.13.4):
```
...........2018-08-01 16:32:25.708459: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
.......Segmentation fault: 11
```
On his system(OSX 10.13.6):
```
..2018-08-01 16:53:55.451451: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
.....Segmentation fault: 11
```
So it seems that problem is not in my broken C API (I know I should fix it, but reinstalling OS is not so easy, moreover it works with Extensor without any problem)

**Comment by anshuman23** [comment]
I think that you are right there are some problems running tests-- I have checked by asking someone else to run the tests on their machine and they fail similarly. I will look into what this problem is and where it is stemming from.

However, despite this, the functionality is working fine on this other machine. Instead of the tests, can you post which functions give you segfaults here and how they were being used? And please run these functions on your colleague's machine which has the Tensorflow C API properly installed.

**Comment by whitered** [comment]
We develop a platform that will run tensorflow functions submitted by third parties. That means that we have no fixed task to be implemented with tensorflow, but we have to provide ability to run any code using the library. At the moment we use simplest examples just to check that our concept works. I suspect that we have segfaults when we use tf sessions. I will send you certain code tomorrow when my colleague will be able to test it.

**Comment by anshuman23** [comment]
I see. I am positive that this issue will be solved if we dig a little deeper. 
And for now, please don't consider the failure of the tests as an indicator of a problem since they are not behaving as intended and I am working to fix them. Also, since the working of Tensorflow C API on your machine seems a bit off, I'd recommend using your colleague's machine for diagnosing the problem with Tensorflex.

Also since you mention segfaults occur when you run sessions, that can be an indicator of a lot of things-- incorrect operation names, wrong input/output tensor type/dimensions, etc. While I am not saying this is the problem in your case, it might be worthwhile to consider that as well. Moreover, if the problems are arising from segfaults from running sessions, you can send me the graph definition .pb binary and I will directly try to run it using the C API based on your input/output types. If it fails there as well then Tensorflex is behaving naturally, otherwise there might be some other issue.

**Comment by anshuman23** [comment]
@whitered thanks for opening this issue up, there were definitely some problems with Tensorflex but the latest PRs have fixed those bugs.

If you like you can clone/pull the repository again and check to see that all the tests are now passing. Moreover, I think you can try to use the latest version of Tensorflex which has the issues covered:
```
{:tensorflex, "~> 0.1.2"}
```

Have a nice day!

**Comment by whitered** [comment]
Yes, I can confirm that tests are passing now. I will definitely see what's new in the latest release. Thanks!
